[package]
name = "nekosbest"
description = "nekos.best API wrapper"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
repository = "https://github.com/dblanovschi/nb-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
reqwest = { version="0.11", default-features=false, features=["json"] }
thiserror = "1.0"
serde = { version="1.0", features=["derive"] }

[dev-dependencies]
tokio = { version="1", features=["full"] }
